Controllers/ServicesController.cs
using hotel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace hotel.Controllers
{
    public class ServicesController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        // Отображение страницы услуг
        public ActionResult Services()
        {
            ViewBag.ActiveTab = "services";
            var servicesData = db.Services.ToList();
            ViewBag.Services = servicesData;
            return View();
        }

        // Метод для поиска услуг
        [HttpGet]
        public JsonResult SearchServices(string title)
        {
            var results = db.Services
                .Where(s => s.Title.Contains(title))
                .ToList();

            return Json(results, JsonRequestBehavior.AllowGet);
        }

        // Метод для добавления услуги
        [HttpPost]
        public JsonResult AddService(ServiceModel service)
        {
            if (ModelState.IsValid)
            {
                db.Services.Add(service);
                db.SaveChanges();
                return Json(new { success = true, message = "Услуга добавлена успешно!" });
            }

            return Json(new { success = false, message = "Ошибка добавления услуги!" });
        }
        public JsonResult GetAll()
        {
            var services = db.Services
                .Select(service => new
                {
                    service.Id,
                    service.Title,
                    service.Price,
                    service.Description
                })
                .ToList();

            return Json(services, JsonRequestBehavior.AllowGet);
        }

        // Метод для изменения услуги
        [HttpPost]
        public JsonResult UpdateService(ServiceModel service)
        {
            if (ModelState.IsValid)
            {
                var existingService = db.Services.Find(service.Id);
                if (existingService != null)
                {
                    existingService.Title = service.Title;
                    existingService.Description = service.Description;
                    existingService.Price = service.Price;

                    db.SaveChanges();
                    return Json(new { success = true, message = "Услуга обновлена успешно!" });
                }

                return Json(new { success = false, message = "Услуга не найдена!" });
            }

            return Json(new { success = false, message = "Некорректные данные!" });
        }

        // Метод для удаления услуги
        [HttpPost]
        public JsonResult DeleteService(int id)
        {
            var service = db.Services.Find(id);
            if (service != null)
            {
                db.Services.Remove(service);
                db.SaveChanges();
                return Json(new { success = true, message = "Услуга удалена успешно!" });
            }

            return Json(new { success = false, message = "Услуга не найдена!" });
        }
    }

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru-ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <link href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
    @RenderSection("scripts", required: false)

</head>
<body>
    <div class="container-fluid p-0 m-0">
        <div class="row " style="box-sizing: border-box;">
            <header class="justify-content-end position-fixed d-flex sidebar header z-2 ">
                    @Html.Partial("_LoginPartial")
            </header>
        </div>

        <div class="row">
            <div class="col-2 p-0 ">
                <div class="col-2 p-0 sidebar position-fixed h-100 z-2">
                    <div class="flex-row p-3 ps-5 logo fs-3">Royal Palace Inn</div>
                    <br />
                    <br />
                    <div class="flex-row p-3 @(ViewBag.ActiveTab == "bookings" ? "active" :"")  ">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" width="80" height="40">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5m-9-6h.008v.008H12v-.008zM12 15h.008v.008H12V15zm0 2.25h.008v.008H12v-.008zM9.75 15h.008v.008H9.75V15zm0 2.25h.008v.008H9.75v-.008zM7.5 15h.008v.008H7.5V15zm0 2.25h.008v.008H7.5v-.008zm6.75-4.5h.008v.008h-.008v-.008zm0 2.25h.008v.008h-.008V15zm0 2.25h.008v.008h-.008v-.008zm2.25-4.5h.008v.008H16.5v-.008zm0 2.25h.008v.008H16.5V15z" />
                        </svg>
                        @Html.ActionLink("Бронирования", "Index", "Home")
                    </div>
                    <div class="flex-row p-3 @(ViewBag.ActiveTab == "clients" ? "active" :"")">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" width="80" height="40">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M18 18.72a9.094 9.094 0 003.741-.479 3 3 0 00-4.682-2.72m.94 3.198l.001.031c0 .225-.012.447-.037.666A11.944 11.944 0 0112 21c-2.17 0-4.207-.576-5.963-1.584A6.062 6.062 0 016 18.719m12 0a5.971 5.971 0 00-.941-3.197m0 0A5.995 5.995 0 0012 12.75a5.995 5.995 0 00-5.058 2.772m0 0a3 3 0 00-4.681 2.72 8.986 8.986 0 003.74.477m.94-3.197a5.971 5.971 0 00-.94 3.197M15 6.75a3 3 0 11-6 0 3 3 0 016 0zm6 3a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0zm-13.5 0a2.25 2.25 0 11-4.5 0 2.25 2.25 0 014.5 0z" />
                        </svg>
                        @Html.ActionLink("Клиенты", "Clients", "Home")
                    </div>
                    <div class="flex-row p-3 @(ViewBag.ActiveTab == "services" ? "active" :"")">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" width="80" height="40">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M21.75 6.75a4.5 4.5 0 01-4.884 4.484c-1.076-.091-2.264.071-2.95.904l-7.152 8.684a2.548 2.548 0 11-3.586-3.586l8.684-7.152c.833-.686.995-1.874.904-2.95a4.5 4.5 0 016.336-4.486l-3.276 3.276a3.004 3.004 0 002.25 2.25l3.276-3.276c.256.565.398 1.192.398 1.852z" />
                            <path stroke-linecap="round" stroke-linejoin="round" d="M4.867 19.125h.008v.008h-.008v-.008z" />
                        </svg>
                        @Html.ActionLink("Услуги", "Services", "Services")
                    </div>
                    <div class="flex-row p-3 @(ViewBag.ActiveTab == "discount" ? "active" :"")">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" width="80" height="40">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M21 11.25v8.25a1.5 1.5 0 01-1.5 1.5H5.25a1.5 1.5 0 01-1.5-1.5v-8.25M12 4.875A2.625 2.625 0 109.375 7.5H12m0-2.625V7.5m0-2.625A2.625 2.625 0 1114.625 7.5H12m0 0V21m-8.625-9.75h18c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125h-18c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z" />
                        </svg>
                        @Html.ActionLink("Скидки", "Discount", "Home")
                    </div>
                    <div class="flex-row p-3 @(ViewBag.ActiveTab == "rooms" ? "active" :"")">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" width="80" height="40">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
                        </svg>
                        @Html.ActionLink("Номера", "Rooms", "Home")
                    </div>
                </div>
            </div>
            <div class="col-10">
                
                    <div class="content container-fluid p-0">
                        @RenderBody()
                    </div>
                
            </div>
        </div>

    </div>


</body>
</html>